# time before autoboot
timeout: 0

/kaworu
    protocol: limine
    # path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/kaworu
    # command line arguments
    cmdline: loglevel=1
